[default]
SECRET_KEY = 'H5S#8#2@!9=68*9()876kKDH'
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = ['app.routes:init_app', 'app.extensions:init_app']
STATIC_FOLDER = "static"


[development]
SQLALCHEMY_DATABASE_URI = "sqlite:///Hub.sqlite"